# Generated by Django 3.2.9 on 2021-11-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='picture')),
                ('tag', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
